- hosts: all
  roles:
    - role: preinstall
  gather_facts: true
  any_errors_fatal: true

- hosts: ceph_nodes
  roles:
    - role: cephadm
  gather_facts: true
  any_errors_fatal: true

- hosts: ceph_nodes
  roles:
    - role: cephadm
  gather_facts: true
  any_errors_fatal: true

