- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

# - name: Set hostname
#   command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ inventory_hostname }} {{ private_ip }}"
    state: present

- name: Install neccessary packages
  dnf:
    name:
      - git
      - vim
      - lvm2
      - wget
      - curl
      - nload
      - chrony
      - podman
      - python3
      - python3-pip
      - iptables-services
    state: present

- name: start and enable chronyd
  service:
    name: chronyd
    state: started
    enabled: true

- name: start and enable iptables
  service:
    name: iptables
    state: started
    enabled: true

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: disabled

- name: Reboot servers and wait for reboot
  reboot:
