# curl-based installation

- name: Download cephadm binary
  ansible.builtin.get_url:
    url: "{{ cephadm_url }}"
    dest: "{{ cephadm_destination }}"
    mode: 0755

- name: Add repository
  shell: "{{ cephadm_destination }} add-repo --release {{ ceph_release_name }}"

- name: Install cephadm
  shell: "{{ cephadm_destination }} install"

- name: Get cephadm version to ensure installation was successful
  shell: cephadm version
  register: cephadm_version

- name: Print cephadm version
  debug:
    msg: "{{ cephadm_version.stdout }}"

